pagopa/rtd-ms-file-reporter

- Dockerfile
> chore: [RTD-888] add dockerfile

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- .github/workflows/anchore.yml
- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .releaserc.json
- manifests/deployment.yml
- manifests/service.yml
This PR adds the CI/CD pipelines, github actions and manifests.
> chore: [RTD-880] add definition of CI/CD pipelines and actions

- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileMetadata.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReport.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReportAggregator.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/repository/FileReportRepository.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReportAggregatorTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReportTest.java
This PR adds the core domain classes representing the model and repo of the file report.
- add models
- add repository
- add unit tests
> [RTD-884] define domain model and repository

- manifests/deployment.yml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReport.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReportAggregator.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportServiceImpl.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/TestUtils.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/service/FileReportServiceImplTest.java
This PR proposes to add the service implementation for the basic retrieve of file report use case.
- add service and implementation
- remove env reference from deployment
- fix a bug in file report model
> [RTD-882] implement service for basic use case

- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/configuration/AppConfiguration.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReport.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportDao.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportEntity.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportRepositoryImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/model/FileReportEntity.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/model/FileReportEntityMapper.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/FileReportControllerImplTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReportAggregatorTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportDaoTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportRepositoryImplTest.java
- src/test/resources/application.yml
This PR proposes to implement the repository for the retrieve of a file-report.
- add repository and dao
- add unit and narrow integration tests
The file-reporter needs to connect to a cosmos mongodb database to retrieve the file-report for each sender.
> [RTD-883] implement repository

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/configuration/AppConfiguration.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/FileReportControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/model/FileReportDto.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/model/FileReportDtoMapper.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportRepositoryImpl.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/FileReportControllerImplTest.java
This PR renames the field in dto `filesUploaded` into `filesRecentlyUploaded`. By consequence the property has been added to the mapper for a proper conversion from domain pojo to dto pojo.
- rename field in dto
- add dedicated mapper for dto
The field is better self explanatory with the new naming.
> [RTD-952] renaming field in dto

- manifests/deployment.yml
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/configuration/AppConfiguration.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/FileReportController.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/FileReportControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/model/FileMetadataDto.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/model/FileReportDto.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/model/FileReportDtoMapper.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileMetadata.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReport.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReportAggregator.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/repository/FileReportRepository.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportServiceImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportDao.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportRepositoryImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/model/FileReportEntity.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/model/FileReportEntityMapper.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/TestUtils.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/FileReportControllerImplTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReportAggregatorTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReportTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportDaoTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportRepositoryImplTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/service/FileReportServiceImplTest.java
- src/test/resources/application.yml
This PR proposes to add the file report feature.
- add controller, service, repository for file report
the file reporter needs to expose a rest API to retrieve the file report from a cosmos mongodb collection.
> feat: add rest API for file report

- src/main/resources/application.yml
This PR proposes to add the configuration for the projector queue.
- add secret reference
- add consumer configuration
The file-reporter needs to connect to the projector queue as consumer.
> [RTD-885] connect micro service to projector queue

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/FileReportControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportServiceImpl.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/FileReportControllerImplTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/service/FileReportServiceImplTest.java
This PR proposes a refactor on a service method name.
The new name is better self explanatory and avoid conflict with future retrieve of single sender code report
> [RTD-1016] refactor service method name

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/repository/FileReportRepository.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportServiceImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportDao.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportRepositoryImpl.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportRepositoryImplTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/service/FileReportServiceImplTest.java
This PR adds the service to retrieve a file report from a single sender code.
- add repository, service and dao methods
- unit tests
A single file report related to a sender code must be retrieved when an event come.
> [RTD-1025] add get file report service

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/repository/FileReportRepository.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportServiceImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportRepositoryImpl.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportRepositoryImplTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/service/FileReportServiceImplTest.java
This PR adds the save method on service and repository.
- add method on service
- add method on repository
The reports needs to be saved after they have been modified when an event comes.
> [RTD-1017] add save method on service and repository

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileStatusEnum.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/model/EventStatusEnum.java
This PR proposes to add the enums for the state management of the files.
- add event states
- add domain states
The file reporter receive from the file register (through event) a set of possible states. Then the state is remapped in another set of states, exposed on the file reporter swagger. In this way the file reporter has the ownership of the states exposed by his own API. 
On the other hand the mapping requires an extra effort in updating the states whenever the changes occurs (it is an unfrequent change tho).
> [RTD-1026] add state enums

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/model/ProjectorEventDto.java
This PR proposes to add the model of the event received on the projector queue.
- add model
The model is needed to map the json received from the queue.
> [RTD-1019] add event model

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileMetadata.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReport.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/repository/FileReportRepository.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportServiceImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportRepositoryImpl.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/FileReportControllerImplTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReportTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/FileReportRepositoryImplTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/service/FileReportServiceImplTest.java
This PR proposes to refactor and add new functionalities on the domain model.
- adapt models to new state enum
- add removeFiles based on expiring date feature
- update unit tests
The event from queue triggers a changes on the domain and therefore it is needed to prepare the functionalities.
> [RTD-1015] refine domain model

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReport.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/model/EventToDomainMapper.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/model/ProjectorEventDto.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/model/EventToDomainMapperTest.java
This PR proposes to add the mapper from event to domain model.
- add mapper
The dto received from the queue must be converted to the domain model.
> [RTD-1018] add mapper event to domain

- .github/workflows/anchore.yml
- manifests/deployment.yml
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/configuration/AppConfiguration.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/FileReportCommandFactory.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/FileReportStrategy.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/EventHandler.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/FileReportEventAdapter.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/persistance/model/FileReportEntityMapper.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/config/KafkaTestConfiguration.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/EventHandlerTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/FileReportEventAdapterTest.java
- src/test/resources/application.yml
This PR proposes to add the consumer of projector queue and its logic.
- add consumer and logic
- add unit tests
- add secret reference to projector queue in deployment file
The event, once read from queue, must be processed.
> [RTD-886] add consume logic

- pom.xml
This PR proposes to align the pom version to 1.0.1.
- upgrade pom version
> chore: [RTD-1122] upgrade pom version

- pom.xml
This PR proposes to promote from dev to uat.
> chore: [RTD-1122] upgrade pom version (#22)

- README.md
This PR serves to trigger the release and allow the realign of pom version with release. Therefore it is marked as `fix`
> fix: [RTD-1122] update README.md

- README.md
This PR serves to trigger the release and allow the realign of pom version with release. Therefore it is marked as fix
> fix: promotion to UAT

- README.md
- pom.xml
This PR proposes to promote to PROD a change aimed to trigger the release action to realign the pom version to release version.
> fix: Promotion To Prod

- pom.xml
- src/main/resources/application.yml
This PR adds and enables health probes provided by spring actuator
> chore: [RTD-1133] Add spring actuator health probes

- .devops/cstar-rtd-code-review-pipelines.yml
- .devops/cstar-rtd-deploy-pipelines.yml
- helm/rtd/.helmignore
- helm/rtd/Chart.yaml
- helm/rtd/values-dev.yaml
- helm/rtd/values-prod.yaml
- helm/rtd/values-uat.yaml
- helm/rtd/values.yaml
This PR adds helm chart and pipelines to deploy to new aks
> chore: [RTD-1081] Helm chart and pipelines

- postman/file_reporter_component_test.postman_collection.postman_collection.json
This PR proposes to add a Postman collection to do component testing on file reporter microservice.
- add Postman collection
With this change we can test file reporter features with Postman collection.
With future works we can include those API calls to CI/CD pipelines.
> chore: [RTD-1102] Add Postman collection

- Dockerfile
- src/main/resources/application.yml
This PR proposes to bump Application Insights agent version.
Also WARN logging level is set for kafka.
> chore: [RTD-1218] Bump Application Insights agent version

- pom.xml
This PR proposes to realign the pom version with the current release.
> chore: [RTD-1449] realign pom version to current release

- helm/rtd/values.yaml
> fix: [RTD-1459] Fix AppInsights problem

- .github/workflows/release.yml
> chore: [RTD-1531] update checkout version

- .devops/cstar-rtd-code-review-pipelines.yml
> chore: code review pipeline trigger

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/FileReportController.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/FileReportControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportServiceImpl.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/FileReportControllerImplTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/service/FileReportServiceImplTest.java
This PR proposes to expose the REST controller to retrieve the ade ack list for a list of senders.
> [RTD-1042] add ade ack controller and service

- pom.xml
> fix: align pom version for next release

- Dockerfile
- helm/rtd/values.yaml
- pom.xml
This PR adds non root user runtime.
> fix: [RTD-1806] Add non-root user runtime

- Dockerfile
- helm/rtd/values.yaml
- pom.xml
* [RTD-1806] run container as non-root
* [RTD-1806] bump version
* [RTD-1806] fix Dockerfile
* [RTD-1806] fix Dockerfile
[RTD-1806]: https://pagopa.atlassian.net/browse/RTD-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1806]: https://pagopa.atlassian.net/browse/RTD-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1806]: https://pagopa.atlassian.net/browse/RTD-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1806]: https://pagopa.atlassian.net/browse/RTD-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Promote to UAT - Add non-root user runtime

- Dockerfile
- helm/rtd/values.yaml
- pom.xml
This PR proposes to update spring boot and its dependencies
package | old version | new version
-- | -- | --
spring boot | 3.1.1 | 3.1.2
spring cloud | 2022.0.2 | 2022.0.4
snakeyaml | 2.0 | 2.1
run image | amazoncorretto:17.0.7-al2023-headless | amazoncorretto:17.0.8-alpine3.18
appinsights | 3.4.14 | 3.4.15
testcontainers | 1.17.6 | 1.18.3
> chore: [RTD-1879] update docker file and dependencies

- pom.xml
package | old version | new version
-- | -- | --
spring boot | 3.1.2 | 3.1.3
> chore: [RTD-1879] insert kafka.version in properties list

- .github/workflows/anchore.yml
- pom.xml
> Promote to PROD

- .github/workflows/anchore.yml
This PR is about to fix a bug inside the payload to publish on the Slack channel.
> chore: [RTD-2095] fix bug

- .github/workflows/scan.yml
- Dockerfile
- pom.xml
This PR proposes to update the kafka dependency version to fix the snappy cve on it.
- replace grype with trivy
- update kafka dependency
> fix: [RTD-2132] update kafka dependency for snappy CVE

- .github/workflows/scan.yml
- Dockerfile
- pom.xml
> fix: promotion to uat - update kafka dependency

- .github/workflows/anchore.yml
- .github/workflows/scan.yml
- Dockerfile
- pom.xml
- update kafka
- change grype with trivy
> fix: Promote to PROD - update kafka

- pom.xml
This PR proposes to rollback to `beta.11` version of azure otel exporter since the `beta.12` version is an intermediate version and does not work properly.
The commit tag is feat to correct the previous `fix` used for otel instrumentation. It had to be `feat`.
> feat: rollback version of azure-monitor-opentelemetry-exporter

- pom.xml
> feat: promotion to uat - azure- otel exporter rollback

- helm/rtd/values.yaml
- pom.xml
- src/main/resources/logback-spring.xml
> fix: [RTD-2261] Wrong otel logging level (#102)

- Dockerfile
This PR proposes to update the runtime docker image to solve the following CVE:
- https://avd.aquasec.com/nvd/cve-2023-5678
- https://avd.aquasec.com/nvd/cve-2023-5363
> fix: [RTD-2296] update runtime docker image to solve cve

- helm/rtd/values-dev.yaml
- helm/rtd/values-uat.yaml
- pom.xml
This PR proposes to enable the forceRedeploy flag in the helm deployment configuration. The pod rollout will happen automatically now and there is no needed of manual deployment restart to spin up the new pods.
> chore: [RTD-2302] enable force redeploy flag

- Dockerfile
- helm/rtd/values-dev.yaml
- helm/rtd/values-uat.yaml
- helm/rtd/values.yaml
- pom.xml
- src/main/resources/logback-spring.xml
This PR proposes to fix the cve on openssl by updating the runtime docker image.
Plus enable forceRedeploy flag
> fix: promotion to UAT - fix cve

- pom.xml
Update dependencies 
| Dependecy | Previews version | Updated version | 
| --- | --- | --- |
| `spring boot` | `3.1.5` | `3.2.1` |
| `spring-cloud` | `2022.0.4` | `2023.0.0` |
| `testcontainers` | `1.19.1` | `1.19.3` |
| `kafka` | `3.6.0` | `3.6.1` |
> chore: [RTD-2308] update version spring boot

- pom.xml
> Promote to uat

- helm/rtd/values-dev.yaml
- helm/rtd/values-prod.yaml
This PR proposes to increase the replicas number to 2 and set the affinity and anti-affinity config in the helm chart to assign each replicas to different nodes.
> chore: [RTD-2325] set pod affinity in prod env

- .github/workflows/scan.yml
- helm/rtd/values-prod.yaml
> chore: promotion to UAT - pod affinity

- helm/rtd/values.yaml
Update startup readiness liveness time params.
> chore: [RTD-2406] update liveness and readiness params

- Dockerfile.native
- pom.xml
This PR proposes to update the spring boot version and the docker image runtime.
dep | old version | new version
-- | -- | --
spring boot | 3.2.1 | 3.2.3
image runtime | ubuntu:noble-20231221 | ubuntu:noble-20240225
> fix: [RTD-2458] update docker image runtime & spring boot

- Dockerfile.native
- helm/rtd/values.yaml
- pom.xml
> fix: promotion to prod - fix cve

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/configuration/AppConfiguration.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/ConsumeEventControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/FileReportCommandFactory.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileMetadata.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/model/FileReport.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/DecryptedEventCommand.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/FileReportEventAdapter.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/model/EventToDomainMapper.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/model/ProjectorEventDto.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/feign/StorageAccountClient.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/DecryptedEventCommandTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/FileReportEventAdapterTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/model/EventToDomainMapperTest.java
This PR proposes to update the business logic for the new report with additional information about the file content.
- separated decrypt command in a dedicated class
- added mock of StorageAccountClient to make the blob get
- breaking change on eventDto name field and refactor mappers accordingly
- added actions on objects domain to support the enrich of a FileMetadata and relative Report
> breaking: [RTD-2467] update business logic

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/ConsumeEventControllerImpl.java
This PR proposes to fix an alert from CodeQL of log injection
> fix: remove log injection

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/controller/ConsumeEventControllerImpl.java
> fix: promotion to UAT 

- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/telemetry/AppInsightConfig.java
- src/main/resources/application.yml
- update OTEL and exporter
- disable metric collection
> chore: [RTD-2480] bump OTEL and exporter version

- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/feign/StorageAccountRestConnector.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/feign/config/ApacheHttpClient5Configuration.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/feign/config/HttpClientConfig.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/telemetry/AppInsightConfig.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/feign/StorageAccountRestConnectorTest.java
This PR proposes to instrument Apache Client 5 with OpenTelemetry.
- change HTTP Client builder to instrumented.
> chore: [RTD-2488] Instrument Apache client

- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .github/workflows/scan.yml
- .github/workflows/send-notification.yml
- Dockerfile.native
- pom.xml
> chore: [RTD-2572] update dependecies, action and images

- .github/workflows/scan.yml
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/domain/service/FileReportServiceImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/event/EventHandler.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/feign/StorageAccountRestConnector.java
> chore: [RTD-290] fix cve and github action

- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/feign/StorageAccountRestConnector.java
Update version spring-boot-starter-web
- modify version on pom.xml
Fix vulnerability of CVE  link: [CVE-2024-50379](https://avd.aquasec.com/nvd/cve-2024-50379)
> fix: [TAE-358] update version spring-boot-starter-web

- .github/workflows/scan.yml
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/feign/StorageAccountRestConnector.java
> fix: [TAE-358] Promotion UAT

- .devops/cstar-rtd-code-review-pipelines.yml
- .devops/cstar-rtd-deploy-pipelines.yml
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfilereporter/telemetry/AppInsightConfig.java
> fix: [TAE-365] Promotion UAT

- Dockerfile
- Dockerfile.native
- pom.xml
Migrated Docker Registry to AWS ECR.
From April 1st unauthenticated and Docker Personal users are subject to a 6-hour pull rate limit on Docker Hub.
https://docs.docker.com/docker-hub/usage/pulls/
> chore: [TAE-367] migrate docker registry to aws
